services:
  angular-app:
    build:
      context: ./dinogame/dino-game
    ports:
      - "80:80"  # Map port 80 (Nginx) to port 4200 on the host
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"  # Expose Node.js server on port 3000
    depends_on:
      - db  # Wait for the database service to be ready
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ct648
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    restart: always

volumes:
  postgres-data:
